// Command genbrowsersessionservices emits browser_session_services_gen.go by
// analyzing BrowserService and nested *Browser*Service types in this module.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"go/types"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"golang.org/x/tools/go/packages"
)

// browserSessionGenLoadStub provides placeholder BrowserSession* service types so
// the kernel package type-checks while this file is regenerated (see Overlay in Generate).
const browserSessionGenLoadStub = `package kernel

import "github.com/kernel/kernel-go-sdk/option"

type BrowserSessionClient struct {
	sessionID  string
	opts       []option.RequestOption
	kernelBase string
	jwt        string
}

func newBrowserSessionClient(sessionID, kernelBase, jwt string, scoped []option.RequestOption) *BrowserSessionClient {
	return &BrowserSessionClient{sessionID: sessionID, opts: scoped, kernelBase: kernelBase, jwt: jwt}
}

type BrowserSessionReplayService struct {
	inner BrowserReplayService
	id    string
}
type BrowserSessionFService struct {
	inner BrowserFService
	id    string
	Watch BrowserSessionFWatchService
}
type BrowserSessionFWatchService struct {
	inner BrowserFWatchService
	id    string
}
type BrowserSessionProcessService struct {
	inner BrowserProcessService
	id    string
}
type BrowserSessionLogService struct {
	inner BrowserLogService
	id    string
}
type BrowserSessionComputerService struct {
	inner BrowserComputerService
	id    string
}
type BrowserSessionPlaywrightService struct {
	inner BrowserPlaywrightService
	id    string
}
`

func main() {
	outPath := flag.String("output", "browser_session_services_gen.go", "path to write generated file (relative to -dir)")
	dir := flag.String("dir", "", "module root (default: working directory)")
	flag.Parse()

	root := *dir
	if root == "" {
		wd, err := os.Getwd()
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		root = wd
	}

	src, err := Generate(root)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	path := *outPath
	if !filepath.IsAbs(path) {
		path = filepath.Join(root, path)
	}
	if err := os.WriteFile(path, src, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

// Generate returns formatted Go source for browser session service wrappers.
func Generate(moduleRoot string) ([]byte, error) {
	genPath := filepath.Join(moduleRoot, "browser_session_services_gen.go")
	genAbs, err := filepath.Abs(genPath)
	if err != nil {
		return nil, err
	}
	cfg := &packages.Config{
		Mode: packages.NeedTypes | packages.NeedImports | packages.NeedName | packages.NeedModule,
		Dir:  moduleRoot,
		Overlay: map[string][]byte{
			// Placeholder types so browser_session.go type-checks while the real file is regenerated.
			genAbs: []byte(browserSessionGenLoadStub),
		},
	}
	pkgs, err := packages.Load(cfg, ".")
	if err != nil {
		return nil, err
	}
	if len(pkgs) != 1 {
		return nil, fmt.Errorf("expected 1 package in %s, got %d", moduleRoot, len(pkgs))
	}
	pkg := pkgs[0]
	if len(pkg.Errors) > 0 {
		return nil, fmt.Errorf("package load errors: %v", pkg.Errors)
	}
	if pkg.Name != "kernel" {
		return nil, fmt.Errorf("expected package kernel, got %s", pkg.Name)
	}

	services, err := discoverBrowserSessionServices(pkg)
	if err != nil {
		return nil, err
	}

	var buf bytes.Buffer
	buf.WriteString(`// Code generated by internal/genbrowsersessionservices; DO NOT EDIT.

package kernel

import (
	"context"
	"io"
	"net/http"

	"github.com/kernel/kernel-go-sdk/option"
	"github.com/kernel/kernel-go-sdk/packages/ssestream"
	"github.com/kernel/kernel-go-sdk/shared"
)
`)

	for _, s := range services {
		emitService(&buf, pkg, s)
	}

	topFields, err := discoverBrowserSessionClientFields(pkg)
	if err != nil {
		return nil, err
	}
	emitBrowserSessionClient(&buf, topFields)

	out := buf.Bytes()
	formatted, err := format.Source(out)
	if err != nil {
		return nil, fmt.Errorf("format: %w\n%s", err, string(out))
	}
	return formatted, nil
}

type serviceInfo struct {
	innerName   string
	sessionName string
	named       *types.Named
	nested      []nestedFieldInfo
}

type nestedFieldInfo struct {
	fieldName string
	inner     *types.Named
	session   string
}

// clientTopField is one exported subresource field on [BrowserSessionClient],
// aligned with a [BrowserService] service field (same name and inner type).
type clientTopField struct {
	fieldName string // e.g. Replays, Fs
	innerName string // e.g. BrowserReplayService
}

func discoverBrowserSessionClientFields(pkg *packages.Package) ([]clientTopField, error) {
	obj := pkg.Types.Scope().Lookup("BrowserService")
	if obj == nil {
		return nil, fmt.Errorf("BrowserService not found")
	}
	named, ok := obj.Type().(*types.Named)
	if !ok {
		return nil, fmt.Errorf("BrowserService is not a named type")
	}
	st, ok := named.Underlying().(*types.Struct)
	if !ok {
		return nil, fmt.Errorf("BrowserService underlying is not a struct")
	}
	var out []clientTopField
	for i := 0; i < st.NumFields(); i++ {
		f := st.Field(i)
		if !f.Exported() || f.Name() == "Options" {
			continue
		}
		nn := derefNamed(f.Type())
		if nn == nil {
			continue
		}
		name := nn.Obj().Name()
		if !strings.HasPrefix(name, "Browser") || !strings.HasSuffix(name, "Service") {
			continue
		}
		out = append(out, clientTopField{fieldName: f.Name(), innerName: name})
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("no browser session subresource fields found on BrowserService")
	}
	return out, nil
}

func emitBrowserSessionClient(buf *bytes.Buffer, top []clientTopField) {
	buf.WriteString(`

// BrowserSessionClient is a browser-scoped view of a browser session. Subresources
// use the session base_url and do not repeat the browser id in method
// signatures. SessionID is exposed for future routing extensions.
type BrowserSessionClient struct {
	sessionID  string
	opts       []option.RequestOption
	kernelBase string
	jwt        string
`)
	for _, f := range top {
		buf.WriteByte('\t')
		buf.WriteString(f.fieldName)
		buf.WriteByte(' ')
		buf.WriteString(sessionWrapperName(f.innerName))
		buf.WriteByte('\n')
	}
	buf.WriteString("}\n")

	buf.WriteString(`
func newBrowserSessionClient(sessionID, kernelBase, jwt string, scoped []option.RequestOption) *BrowserSessionClient {
`)

	hasFS := false
	for _, f := range top {
		if f.innerName == "BrowserFService" {
			hasFS = true
			break
		}
	}
	if hasFS {
		buf.WriteString("\tinnerFs := NewBrowserFService(scoped...)\n")
	}

	buf.WriteString("\treturn &BrowserSessionClient{\n")
	buf.WriteString("\t\tsessionID:  sessionID,\n")
	buf.WriteString("\t\topts:       scoped,\n")
	buf.WriteString("\t\tkernelBase: kernelBase,\n")
	buf.WriteString("\t\tjwt:        jwt,\n")

	for _, f := range top {
		if f.innerName == "BrowserFService" {
			buf.WriteString("\t\tFs: BrowserSessionFService{\n")
			buf.WriteString("\t\t\tinner: innerFs,\n")
			buf.WriteString("\t\t\tid:    sessionID,\n")
			buf.WriteString("\t\t\tWatch: BrowserSessionFWatchService{inner: innerFs.Watch, id: sessionID},\n")
			buf.WriteString("\t\t},\n")
			continue
		}
		wrap := sessionWrapperName(f.innerName)
		newFn := "New" + f.innerName
		buf.WriteByte('\t')
		buf.WriteByte('\t')
		buf.WriteString(f.fieldName)
		buf.WriteString(": ")
		buf.WriteString(wrap)
		buf.WriteString("{inner: ")
		buf.WriteString(newFn)
		buf.WriteString("(scoped...), id: sessionID},\n")
	}
	buf.WriteString("\t}\n}\n")
}

func discoverBrowserSessionServices(pkg *packages.Package) ([]serviceInfo, error) {
	obj := pkg.Types.Scope().Lookup("BrowserService")
	if obj == nil {
		return nil, fmt.Errorf("BrowserService not found")
	}
	named, ok := obj.Type().(*types.Named)
	if !ok {
		return nil, fmt.Errorf("BrowserService is not a named type")
	}

	seen := map[string]*types.Named{}
	var walk func(*types.Named)
	walk = func(n *types.Named) {
		name := n.Obj().Name()
		if name == "BrowserService" {
			// descend without recording
		} else {
			if !strings.HasPrefix(name, "Browser") || !strings.HasSuffix(name, "Service") {
				return
			}
			if _, dup := seen[name]; dup {
				return
			}
			seen[name] = n
		}
		st, ok := n.Underlying().(*types.Struct)
		if !ok {
			return
		}
		for i := 0; i < st.NumFields(); i++ {
			f := st.Field(i)
			if !f.Exported() || f.Embedded() {
				continue
			}
			if f.Name() == "Options" {
				continue
			}
			nn := derefNamed(f.Type())
			if nn == nil {
				continue
			}
			walk(nn)
		}
	}
	walk(named)

	var names []string
	for n := range seen {
		names = append(names, n)
	}
	sort.Strings(names)

	var out []serviceInfo
	for _, name := range names {
		n := seen[name]
		st := n.Underlying().(*types.Struct)
		var nested []nestedFieldInfo
		for i := 0; i < st.NumFields(); i++ {
			f := st.Field(i)
			if !f.Exported() || f.Embedded() || f.Name() == "Options" {
				continue
			}
			nn := derefNamed(f.Type())
			if nn == nil {
				continue
			}
			fn := nn.Obj().Name()
			if !strings.HasPrefix(fn, "Browser") || !strings.HasSuffix(fn, "Service") {
				continue
			}
			if _, ok := seen[fn]; !ok {
				continue
			}
			nested = append(nested, nestedFieldInfo{
				fieldName: f.Name(),
				inner:     nn,
				session:   sessionWrapperName(fn),
			})
		}
		sort.Slice(nested, func(i, j int) bool { return nested[i].fieldName < nested[j].fieldName })
		out = append(out, serviceInfo{
			innerName:   name,
			sessionName: sessionWrapperName(name),
			named:       n,
			nested:      nested,
		})
	}
	return out, nil
}

func sessionWrapperName(innerService string) string {
	mid := strings.TrimSuffix(strings.TrimPrefix(innerService, "Browser"), "Service")
	return "BrowserSession" + mid + "Service"
}

func derefNamed(t types.Type) *types.Named {
	for {
		switch u := t.(type) {
		case *types.Pointer:
			t = u.Elem()
		default:
			n, ok := t.(*types.Named)
			if !ok {
				return nil
			}
			return n
		}
	}
}

func emitService(buf *bytes.Buffer, pkg *packages.Package, s serviceInfo) {
	buf.WriteString("\n// ")
	buf.WriteString(s.sessionName)
	buf.WriteString(" exposes browser session APIs without passing browser id.\n")
	buf.WriteString("type ")
	buf.WriteString(s.sessionName)
	buf.WriteString(" struct {\n")
	buf.WriteString("\tinner ")
	buf.WriteString(s.innerName)
	buf.WriteString("\n")
	buf.WriteString("\tid    string\n")
	for _, nf := range s.nested {
		buf.WriteString("\t")
		buf.WriteString(nf.fieldName)
		buf.WriteString(" ")
		buf.WriteString(nf.session)
		buf.WriteString("\n")
	}
	buf.WriteString("}\n")

	ms := types.NewMethodSet(types.NewPointer(s.named))
	var methods []*types.Func
	for i := 0; i < ms.Len(); i++ {
		sel := ms.At(i)
		fn, ok := sel.Obj().(*types.Func)
		if !ok || !fn.Exported() {
			continue
		}
		methods = append(methods, fn)
	}
	sort.Slice(methods, func(i, j int) bool { return methods[i].Name() < methods[j].Name() })

	for _, fn := range methods {
		sig := fn.Type().(*types.Signature)
		emitMethod(buf, pkg, s.sessionName, sig, fn.Name())
	}
}

// writeWrapperSignature writes "(params) results" for a browser session wrapper method.
// go/types.WriteSignature encodes final variadic parameters as slices; callers expect
// "opts ...option.RequestOption" like the underlying Stainless services.
func writeWrapperSignature(buf *bytes.Buffer, sig *types.Signature, q types.Qualifier) {
	buf.WriteByte('(')
	params := sig.Params()
	for i := 0; i < params.Len(); i++ {
		if i > 0 {
			buf.WriteString(", ")
		}
		p := params.At(i)
		if p.Name() != "" {
			buf.WriteString(p.Name())
			buf.WriteByte(' ')
		}
		if sig.Variadic() && i == params.Len()-1 {
			slice := p.Type().(*types.Slice)
			buf.WriteString("...")
			buf.WriteString(types.TypeString(slice.Elem(), q))
			continue
		}
		buf.WriteString(types.TypeString(p.Type(), q))
	}
	buf.WriteByte(')')
	writeResults(buf, sig.Results(), q)
}

func writeResults(buf *bytes.Buffer, results *types.Tuple, q types.Qualifier) {
	switch results.Len() {
	case 0:
		return
	case 1:
		r := results.At(0)
		if r.Name() == "" {
			buf.WriteByte(' ')
			buf.WriteString(types.TypeString(r.Type(), q))
			return
		}
		fallthrough
	default:
		buf.WriteString(" (")
		for i := 0; i < results.Len(); i++ {
			if i > 0 {
				buf.WriteString(", ")
			}
			r := results.At(i)
			if r.Name() != "" {
				buf.WriteString(r.Name())
				buf.WriteByte(' ')
			}
			buf.WriteString(types.TypeString(r.Type(), q))
		}
		buf.WriteByte(')')
	}
}

func emitMethod(buf *bytes.Buffer, pkg *packages.Package, sessionName string, innerSig *types.Signature, methodName string) {
	params := innerSig.Params()
	if params.Len() < 1 || !isContext(params.At(0).Type()) {
		return
	}

	qual := qualifier(pkg.Types)
	wrapperSig := types.NewSignature(nil, wrapperParamTuple(innerSig), innerSig.Results(), innerSig.Variadic())

	var preStmts []string
	var callArgs []string
	callArgs = append(callArgs, "ctx")

	for i := 1; i < params.Len(); i++ {
		p := params.At(i)
		pname := paramName(p, i)
		if isVariadicOpts(innerSig, i) {
			callArgs = append(callArgs, pname+"...")
			break
		}
		if p.Name() == "id" && isStringType(p.Type()) {
			callArgs = append(callArgs, "s.id")
			continue
		}
		if hasStringIDField(p.Type()) {
			preStmts = append(preStmts, fmt.Sprintf("\t%s.ID = s.id", pname))
			callArgs = append(callArgs, pname)
			continue
		}
		callArgs = append(callArgs, pname)
	}

	fmt.Fprintf(buf, "\nfunc (s %s) %s", sessionName, methodName)
	writeWrapperSignature(buf, wrapperSig, qual)
	buf.WriteString(" {\n")
	for _, ln := range preStmts {
		buf.WriteString(ln)
		buf.WriteByte('\n')
	}
	innerCall := fmt.Sprintf("s.inner.%s(%s)", methodName, strings.Join(callArgs, ", "))
	if innerSig.Results().Len() == 0 {
		fmt.Fprintf(buf, "\t%s\n", innerCall)
	} else {
		fmt.Fprintf(buf, "\treturn %s\n", innerCall)
	}
	buf.WriteString("}\n")
}

// wrapperParamTuple is the inner API signature with the browser id path parameter removed.
func wrapperParamTuple(sig *types.Signature) *types.Tuple {
	params := sig.Params()
	var vars []*types.Var
	vars = append(vars, params.At(0))
	last := params.Len() - 1
	for i := 1; i < params.Len(); i++ {
		p := params.At(i)
		if sig.Variadic() && i == last {
			vars = append(vars, p)
			break
		}
		if p.Name() == "id" && isStringType(p.Type()) {
			continue
		}
		vars = append(vars, p)
	}
	return types.NewTuple(vars...)
}

func paramName(p *types.Var, idx int) string {
	if p.Name() != "" {
		return p.Name()
	}
	return fmt.Sprintf("arg%d", idx)
}

func isVariadicOpts(sig *types.Signature, idx int) bool {
	if !sig.Variadic() || idx != sig.Params().Len()-1 {
		return false
	}
	_, ok := sig.Params().At(idx).Type().(*types.Slice)
	return ok
}

func isContext(t types.Type) bool {
	named, ok := t.(*types.Named)
	if !ok {
		return false
	}
	return named.Obj().Pkg() != nil && named.Obj().Pkg().Path() == "context" && named.Obj().Name() == "Context"
}

func isStringType(t types.Type) bool {
	b, ok := t.Underlying().(*types.Basic)
	return ok && b.Kind() == types.String
}

func hasStringIDField(t types.Type) bool {
	str, ok := derefStruct(t)
	if !ok {
		return false
	}
	for i := 0; i < str.NumFields(); i++ {
		f := str.Field(i)
		if f.Name() == "ID" && isStringType(f.Type()) {
			return true
		}
	}
	return false
}

func derefStruct(t types.Type) (*types.Struct, bool) {
	if p, ok := t.(*types.Pointer); ok {
		t = p.Elem()
	}
	switch u := t.(type) {
	case *types.Named:
		s, ok := u.Underlying().(*types.Struct)
		return s, ok
	case *types.Struct:
		return u, true
	default:
		return nil, false
	}
}

func qualifier(pkg *types.Package) types.Qualifier {
	return func(other *types.Package) string {
		if other == pkg {
			return ""
		}
		return other.Name()
	}
}
